#!/bin/bash -l
#SBATCH -N 1
#SBATCH -n 2
#SBATCH -t 5:0
#SBATCH --mem 16G 
#SBATCH --gres=gpu:2

conda deactivate
conda activate jax # activate your favorite jax env

srun -n 2 python -u run.py > log.out
